import { USER_PROFILE_PAGE_TITLE } from "../../Pages/user-module/Profile";
import { USER_FORGOT_PASSWORD_PAGE_TITLE } from "../../Pages/user-module/ResetPassword";
import { BIOMETRIC_DATA_UPLOAD_PAGE_TITLE } from "../../Pages/BiometricTables/DataUpload";
import { USER_CREATE_REPORTING_MANAGER_PAGE_TITLE } from "../../Pages/User-Information/CreationPages/ReportingManager";
import { USER_CREATE_SHIFT_TIMING_PAGE_TITLE } from "../../Pages/User-Information/CreationPages/ShiftTimings";
import { USER_CREATE_WORKING_LOCATION_PAGE_TITLE } from "../../Pages/User-Information/CreationPages/WorkInfo";

import { CREATE_EMPLOYEE_PAGE_TITLE } from "../../Pages/Employee/CreateEmployee";
import { EMPLOYEE_AFTER_CLICKING_EMPLOYEE_TABLE_PAGE_TITLE } from "../../Pages/Employee/Employee";
import { EMPLOYEE_TABLE_PAGE_TITLE } from "../../Pages/Employee/Employees";

import { EMPLOYEE_SHIFT_TIMING_TABLE_TITLE } from "../../Pages/User-Information/Tables/EmpShiftTime";
import { EMPLOYEE_WORKING_LOCATION_TABLE_TITLE } from "../../Pages/User-Information/Tables/EmpWorkLocation";
import { EMPLOYEE_REPORTING_MANAGER_TABLE_TITLE } from "../../Pages/User-Information/Tables/ReportingMangr";


import { ACCESS_LEVEL_FIRST_BIOMETRIC_TABLE_TITLE } from "../../Pages/BiometricTables/BiometricSearch";
import { ACCESS_LEVEL_THIRD_BIOMETRIC_TABLE_TITLE } from "../../Pages/BiometricTables/BiometricTableAfterClickingView";
import { EMPLOYEE_LEVEL_THIRD_BIOMETRIC_TABLE_TITLE } from "../../Pages/BiometricTables/EmpBioTableAfterClickingView";

import { DAILY_TASK_CREATION_TITLE } from "../../Pages/TaskDetails/DailyReport";
import { EMPLOYEE_TASK_SEARCH_TITLE } from "../../Pages/TaskDetails/EmpTaskDetails";
import { EMPLOYEE_LEVEL_TASK_DETAILS_ELABORATELY_TITLE } from "../../Components/TaskComponent/EmpTaskDetailsElaborately";

import { ACCESS_LEVEL_TASK_STATUS_TITLE } from "../../Pages/TaskDetails/TaskStatus";
import { ACCESS_LEVEL_VERIFICATION_PENDING_TABLE_TITLE } from "../../Pages/TaskDetails/VerificationPending";
import { ACCESS_LEVEL_TASK_DETAILS_ELABORATELY_TITLE } from "../../Components/TaskComponent/TaskDetailsElaborately";

import { ACCESS_LEVEL_SHIFT_TIMING_TABLE_TITLE } from "../../Pages/Access-Level-Pages/Tables-EmployeeDataFromProfile/EmpShiftTimingfromProfileData";
import { ACCESS_LEVEL_WORKING_LOCATION_TABLE_TITLE } from "../../Pages/Access-Level-Pages/Tables-EmployeeDataFromProfile/EmpWorkLocationFromProfile";
import { ACCESS_LEVEL_REPORTING_MANAGER_TABLE_TITLE } from "../../Pages/Access-Level-Pages/Tables-EmployeeDataFromProfile/ReportingManagerFromProfileData";
import { ACCESS_LEVEL_CREATE_REPORTING_MANAGER_TITLE } from "../../Pages/Access-Level-Pages/Creation-Pages/AccessReportingManager";
import { ACCESS_LEVEL_CREATE_SHIFT_TIMING_TITLE } from "../../Pages/Access-Level-Pages/Creation-Pages/AccessShiftTimings";
import { ACCESS_LEVEL_CREATE_WORKING_LOCATION_TITLE } from "../../Pages/Access-Level-Pages/Creation-Pages/AccessWorkInfo";
import { EMPLOYEE_DELETE_BUTTON } from "../../Pages/Employee/Employees";
import { ACCESS_UPDATE_EMPLOYEE_MODAL } from "../../Pages/Employee/Employee";
import { ACCESS_UPDATE_CONTACT_MODAL } from "../../Pages/Employee/Employee";
import { ACCESS_LEVEL_REPORTING_MANAGER_MODAL } from "../../Pages/Employee/Employee";
import { ACCESS_LEVEL_WORKING_LOCATION_MODAL } from "../../Pages/Employee/Employee";
import { ACCESS_LEVEL_SHIFT_TIMING_MODAL } from "../../Pages/Employee/Employee";


import { LEAVES_DATA_UPLOAD_PAGE_TITLE } from "../../Pages/Leaves/LeaveDataUpload";
import { ALL_EMPLOYEE_LEAVES_REPORT_PAGE_TITLE } from "../../Pages/Leaves/LeavesReport";
import { EMPLOYEE_LEAVES_SPENT_PAGE_TITLE } from "../../Pages/Leaves/EmployeeLeaveSpent";
import { EMPLOYEE_LEAVES_SPENT_AFTER_ROW_CLICK_PAGE_TITLE } from "../../Pages/Leaves/EmployeeleavesAfterRowClick";
import { LEAVES_DATA_UPLOAD_AS_PER_BAND_PAGE_TITLE } from "../../Pages/Leaves/LeavesAsPerBand";

import { REPORTED_EMPLOYEES_PAGE_TITLE } from "../../Pages/ReportingManager/ReportingEmployees";
import { REPORTED_EMPLOYEE_PROFILE_PAGE_TITLE } from "../../Pages/ReportingManager/ReportingEmpProfile";
import { ACCESS_LEVEL_PROFILE_PHOTO_UPLOAD } from "../../Pages/Employee/Employee";


import { REPORTING_EMPLOYEE_SHOW_EMP_ID } from "../../Pages/ReportingManager/ReportingEmployees";
import { EMPLOYEE_BIOMETRIC_STATUS_FIRST_PAGE_TITLE } from "../../Pages/BiometricTables/BiometricReport1";
import { BIOMETRIC_REPORT_DETAILED_VIEW_PAGE_TITLE } from "../../Pages/BiometricTables/BiometricReportDetails";
import { ALL_EMPLOYEE_MISSING_REPORT_PAGE_TITLE } from "../../Pages/BiometricTables/MissingReports/AccessLevelMissingReportSearch";
import { ALL_EMPLOYEE_MISSING_REPORT_AFTER_CLICK_PAGE_TITLE } from "../../Pages/BiometricTables/MissingReports/AccesslLevelMissingReports";

// warning mails
import { WARNING_MAILS_CREATION_PAGE_TITLE } from "../../Pages/WarningMails/CreateWarningMails";
import { ALL_EMPLOYEE_WARNING_MAILS_PAGE_TITLE } from "../../Pages/WarningMails/WarningMailSearch";
import { PARTICULAR_EMPLOYEE_WARNING_MAILS_PAGE_TITLE } from "../../Pages/WarningMails/WarnigMaillTable";

import { ACCESS_LEVEL_WARNING_MAIL_SEARCH_GIVEN_DATES_PAGE_TITLE } from "../../Pages/WarningMails/AllWarningMailReportsWithSearch";

import { REVIEW_RATING_CREATION_PAGE_TITLE } from "../../Pages/Rating/EmpReviewRating";
import { PARTUCULAR_EMPLOYEE_REVIEW_RATING_TABLE_TITLE } from "../../Pages/Rating/EmpReviewModule";
import { ALL_EMPLOYEE_REVIEW_RATING_SYSTEM_PAGE_TITLE } from "../../Pages/Rating/AllEmpReviewRating";
import { ACCESS_LEVEL_GIVEN_TABLE_PAGE_TITLE } from "../../Pages/AccessTables/EmpAccess";
import { EMPLOYEE_ACCESS_CREATION_PAGE_TITLE } from "../../Pages/AccessTables/EmpAccessModal";
import { CREATE_SKILL_REPORT_PAGE_TITLE } from "../../Pages/EmpSkillReport/CreateReport";
import { PARTICULAR_EMPLOYEE_SKILL_REPORT_PAGE_TITLE } from "../../Pages/EmpSkillReport/Skills";
import { ALL_EMPLOYEES_SKILL_REPORT_PAGE_TITLE } from "../../Pages/EmpSkillReport/EmployeeSkillsReport";
import { REPORTING_MANAGER_CREATE_SKILL_REPORT_PAGE_TITLE } from "../../Pages/EmpSkillReport/ReportingManagerCreateSkill";
import { LEAVE_DATA_CREATION_PAGE_TITLE } from "../../Pages/Leaves/LeaveCreation";

import {BIOMETRIC_TABLE_DATA_AFTER_FIRST_1_PAGE_TITLE} from "../../Pages/BiometricTables/BiometricTable"
import { ALL_EMPLOYEE_TERMINATION_PAGE_TITLE } from "../../Pages/Employee/TerminatedEmployee/TerminationTable";
import { EMPLOYEE_RATING_EDIT_DELETE_OPTION_PAGE_TITLE } from "../../Pages/Rating/EmpReviewModule";
import { HOLIDAYLIST_FOR_ALLEMPLOYEES, HOLIDAYLIST_FOR_ALLEMPLOYEES_WITH_EDIT_BUTTON } from "../../Pages/Holiday/HolidayTable";
import { EMPLOYEES_DATE_OF_BIRTH_UPLOAD } from "../../Pages/Employee/EmployeesDateOfBirth";
import { ADD_LEAVES_TYPE_ADMIN } from "../../Pages/Leaves(Beta)/LeaveTypeTable";
import { APPLY_LEAVE_BY_HR } from "../../Pages/Leaves(Beta)/LeaveApplyByHr";
import { HR_VIEW_EMPLOYEES_LEAVE_STATUS, REPORTED_MANAGER_EMPLOYEES_LEAVE_STATUS } from "../../Pages/Leaves(Beta)/EmployeesLeaveStatus";
import { REPORTING_MANAGER_PENDING_LEAVES } from "../../Pages/Leaves(Beta)/PendingLeavesForReportingManager";
import { HR_ACCESS_PENDING_LEAVES_STATUS, HR_PENDING_LEAVES, PENDING_LEAVES_DELETE_FROM_BY_HR_LEVEL, PENDING_LEAVES_UPDATE_FROM_BY_HR_LEVEL, PENDING_LEAVES_VIEW_FOR_RM } from "../../Pages/Leaves(Beta)/PendingLeavesForHr";
import { LEAVES_STATUS_VIEW_RM } from "../../Components/Navbar/SideNavBar";
import { LEAVES_BETA_ALL_EMPLOYEES_LEAVES_REPORT } from "../../Pages/Leaves(Beta)/AllEmployeesLeaveReport";
import { REPORTING_EMPLOYEE_LEAVE_REPORT } from "../../Pages/Leaves(Beta)/ReportingEmployeesLeaveReport";
import { EMPLOYEES_WITHOUT_RM } from "../../Pages/Employee/EmployeesWithoutRM/EmployeesWithoutReportingManager";



export const ACCESS_LEVEL_1 = ['1001','1002','1003','1004','1005','1006','1007','1008'];
export const ACCESS_LEVEL_2 = ['1003','1004','1005','1006','1007','1008'];
export const ACCESS_LEVEL_3 = ['1005','1006','1007','1008'];
export const ACCESS_LEVEL_4 = ['1007','1008'];
export const ACCESS_LEVEL_5 = ['1008'];


export const PAGE_ACCESS_LEVEL_MAP=new Map();

//admin level access
PAGE_ACCESS_LEVEL_MAP.set(ACCESS_LEVEL_GIVEN_TABLE_PAGE_TITLE,ACCESS_LEVEL_4);
PAGE_ACCESS_LEVEL_MAP.set(EMPLOYEE_ACCESS_CREATION_PAGE_TITLE,ACCESS_LEVEL_4);
PAGE_ACCESS_LEVEL_MAP.set(ADD_LEAVES_TYPE_ADMIN,ACCESS_LEVEL_4);



//employee level accesss
    PAGE_ACCESS_LEVEL_MAP.set(USER_PROFILE_PAGE_TITLE,ACCESS_LEVEL_1);
    PAGE_ACCESS_LEVEL_MAP.set(USER_FORGOT_PASSWORD_PAGE_TITLE,ACCESS_LEVEL_1);

    PAGE_ACCESS_LEVEL_MAP.set(USER_CREATE_REPORTING_MANAGER_PAGE_TITLE,ACCESS_LEVEL_1);
    PAGE_ACCESS_LEVEL_MAP.set(USER_CREATE_SHIFT_TIMING_PAGE_TITLE,ACCESS_LEVEL_1);
    PAGE_ACCESS_LEVEL_MAP.set(USER_CREATE_WORKING_LOCATION_PAGE_TITLE,ACCESS_LEVEL_1);

    PAGE_ACCESS_LEVEL_MAP.set(EMPLOYEE_SHIFT_TIMING_TABLE_TITLE,ACCESS_LEVEL_1);
    PAGE_ACCESS_LEVEL_MAP.set(EMPLOYEE_WORKING_LOCATION_TABLE_TITLE,ACCESS_LEVEL_1);
    PAGE_ACCESS_LEVEL_MAP.set(EMPLOYEE_REPORTING_MANAGER_TABLE_TITLE,ACCESS_LEVEL_1);


    PAGE_ACCESS_LEVEL_MAP.set(EMPLOYEE_LEVEL_THIRD_BIOMETRIC_TABLE_TITLE,ACCESS_LEVEL_1);

    PAGE_ACCESS_LEVEL_MAP.set(DAILY_TASK_CREATION_TITLE,ACCESS_LEVEL_1);
    PAGE_ACCESS_LEVEL_MAP.set(EMPLOYEE_TASK_SEARCH_TITLE,ACCESS_LEVEL_1);
    PAGE_ACCESS_LEVEL_MAP.set(EMPLOYEE_LEVEL_TASK_DETAILS_ELABORATELY_TITLE,ACCESS_LEVEL_1);
    
    PAGE_ACCESS_LEVEL_MAP.set(EMPLOYEE_LEAVES_SPENT_PAGE_TITLE,ACCESS_LEVEL_1);
    PAGE_ACCESS_LEVEL_MAP.set(EMPLOYEE_BIOMETRIC_STATUS_FIRST_PAGE_TITLE,ACCESS_LEVEL_1);
    PAGE_ACCESS_LEVEL_MAP.set(BIOMETRIC_REPORT_DETAILED_VIEW_PAGE_TITLE,ACCESS_LEVEL_1);

    PAGE_ACCESS_LEVEL_MAP.set(PARTICULAR_EMPLOYEE_WARNING_MAILS_PAGE_TITLE,ACCESS_LEVEL_1);
    PAGE_ACCESS_LEVEL_MAP.set( ALL_EMPLOYEE_MISSING_REPORT_AFTER_CLICK_PAGE_TITLE,ACCESS_LEVEL_1);
    
    PAGE_ACCESS_LEVEL_MAP.set( PARTUCULAR_EMPLOYEE_REVIEW_RATING_TABLE_TITLE,ACCESS_LEVEL_1);
    PAGE_ACCESS_LEVEL_MAP.set(CREATE_SKILL_REPORT_PAGE_TITLE,ACCESS_LEVEL_1);
    PAGE_ACCESS_LEVEL_MAP.set( PARTICULAR_EMPLOYEE_SKILL_REPORT_PAGE_TITLE,ACCESS_LEVEL_1);
    PAGE_ACCESS_LEVEL_MAP.set(HOLIDAYLIST_FOR_ALLEMPLOYEES,ACCESS_LEVEL_1);



    
//Manager Level Access

PAGE_ACCESS_LEVEL_MAP.set(EMPLOYEE_AFTER_CLICKING_EMPLOYEE_TABLE_PAGE_TITLE,ACCESS_LEVEL_2);
PAGE_ACCESS_LEVEL_MAP.set(EMPLOYEE_TABLE_PAGE_TITLE,ACCESS_LEVEL_2);
PAGE_ACCESS_LEVEL_MAP.set(ACCESS_LEVEL_TASK_STATUS_TITLE,ACCESS_LEVEL_2);
PAGE_ACCESS_LEVEL_MAP.set(ACCESS_LEVEL_TASK_DETAILS_ELABORATELY_TITLE,ACCESS_LEVEL_2);
PAGE_ACCESS_LEVEL_MAP.set(REPORTED_EMPLOYEES_PAGE_TITLE,ACCESS_LEVEL_2);
PAGE_ACCESS_LEVEL_MAP.set(REPORTED_EMPLOYEE_PROFILE_PAGE_TITLE,ACCESS_LEVEL_2);
PAGE_ACCESS_LEVEL_MAP.set(EMPLOYEE_LEAVES_SPENT_AFTER_ROW_CLICK_PAGE_TITLE,ACCESS_LEVEL_2);
PAGE_ACCESS_LEVEL_MAP.set(REPORTING_MANAGER_CREATE_SKILL_REPORT_PAGE_TITLE,ACCESS_LEVEL_2);
PAGE_ACCESS_LEVEL_MAP.set(REPORTED_MANAGER_EMPLOYEES_LEAVE_STATUS,ACCESS_LEVEL_2);
PAGE_ACCESS_LEVEL_MAP.set(REPORTING_MANAGER_PENDING_LEAVES,ACCESS_LEVEL_2)
PAGE_ACCESS_LEVEL_MAP.set(LEAVES_STATUS_VIEW_RM,ACCESS_LEVEL_2)
PAGE_ACCESS_LEVEL_MAP.set(PENDING_LEAVES_VIEW_FOR_RM,ACCESS_LEVEL_2)
PAGE_ACCESS_LEVEL_MAP.set(REPORTING_EMPLOYEE_LEAVE_REPORT,ACCESS_LEVEL_2)



//HR Level Access
    PAGE_ACCESS_LEVEL_MAP.set(BIOMETRIC_DATA_UPLOAD_PAGE_TITLE,ACCESS_LEVEL_3);
    PAGE_ACCESS_LEVEL_MAP.set(BIOMETRIC_TABLE_DATA_AFTER_FIRST_1_PAGE_TITLE,ACCESS_LEVEL_3);

    PAGE_ACCESS_LEVEL_MAP.set(CREATE_EMPLOYEE_PAGE_TITLE,ACCESS_LEVEL_3);

    PAGE_ACCESS_LEVEL_MAP.set(ACCESS_LEVEL_FIRST_BIOMETRIC_TABLE_TITLE,ACCESS_LEVEL_3);
    PAGE_ACCESS_LEVEL_MAP.set(ACCESS_LEVEL_THIRD_BIOMETRIC_TABLE_TITLE,ACCESS_LEVEL_3);

    
    PAGE_ACCESS_LEVEL_MAP.set(ACCESS_LEVEL_VERIFICATION_PENDING_TABLE_TITLE,ACCESS_LEVEL_4);
   
    PAGE_ACCESS_LEVEL_MAP.set(ACCESS_LEVEL_SHIFT_TIMING_TABLE_TITLE,ACCESS_LEVEL_3);
    PAGE_ACCESS_LEVEL_MAP.set(ACCESS_LEVEL_WORKING_LOCATION_TABLE_TITLE,ACCESS_LEVEL_3);
    PAGE_ACCESS_LEVEL_MAP.set(ACCESS_LEVEL_REPORTING_MANAGER_TABLE_TITLE,ACCESS_LEVEL_3);
    PAGE_ACCESS_LEVEL_MAP.set(ACCESS_LEVEL_CREATE_REPORTING_MANAGER_TITLE,ACCESS_LEVEL_3);
    PAGE_ACCESS_LEVEL_MAP.set(ACCESS_LEVEL_CREATE_SHIFT_TIMING_TITLE,ACCESS_LEVEL_3);
    PAGE_ACCESS_LEVEL_MAP.set(ACCESS_LEVEL_CREATE_WORKING_LOCATION_TITLE,ACCESS_LEVEL_3);
    PAGE_ACCESS_LEVEL_MAP.set(ACCESS_UPDATE_EMPLOYEE_MODAL,ACCESS_LEVEL_3);
    PAGE_ACCESS_LEVEL_MAP.set(ACCESS_UPDATE_CONTACT_MODAL,ACCESS_LEVEL_3);
    PAGE_ACCESS_LEVEL_MAP.set(ACCESS_LEVEL_REPORTING_MANAGER_MODAL,ACCESS_LEVEL_3);
    PAGE_ACCESS_LEVEL_MAP.set(ACCESS_LEVEL_WORKING_LOCATION_MODAL,ACCESS_LEVEL_3);
    PAGE_ACCESS_LEVEL_MAP.set(ACCESS_LEVEL_SHIFT_TIMING_MODAL,ACCESS_LEVEL_3);

    PAGE_ACCESS_LEVEL_MAP.set(LEAVES_DATA_UPLOAD_PAGE_TITLE,ACCESS_LEVEL_3);
    PAGE_ACCESS_LEVEL_MAP.set( LEAVES_DATA_UPLOAD_AS_PER_BAND_PAGE_TITLE,ACCESS_LEVEL_3);
    PAGE_ACCESS_LEVEL_MAP.set(ALL_EMPLOYEE_LEAVES_REPORT_PAGE_TITLE,ACCESS_LEVEL_3);
    PAGE_ACCESS_LEVEL_MAP.set(ACCESS_LEVEL_PROFILE_PHOTO_UPLOAD,ACCESS_LEVEL_3);

    PAGE_ACCESS_LEVEL_MAP.set(REPORTING_EMPLOYEE_SHOW_EMP_ID,ACCESS_LEVEL_3);
    
    PAGE_ACCESS_LEVEL_MAP.set( ALL_EMPLOYEE_MISSING_REPORT_PAGE_TITLE,ACCESS_LEVEL_3);
    PAGE_ACCESS_LEVEL_MAP.set(ACCESS_LEVEL_WARNING_MAIL_SEARCH_GIVEN_DATES_PAGE_TITLE,ACCESS_LEVEL_3);

    PAGE_ACCESS_LEVEL_MAP.set(REVIEW_RATING_CREATION_PAGE_TITLE,ACCESS_LEVEL_3);

    PAGE_ACCESS_LEVEL_MAP.set(ALL_EMPLOYEE_REVIEW_RATING_SYSTEM_PAGE_TITLE,ACCESS_LEVEL_3);
    PAGE_ACCESS_LEVEL_MAP.set( ALL_EMPLOYEES_SKILL_REPORT_PAGE_TITLE,ACCESS_LEVEL_3);
    PAGE_ACCESS_LEVEL_MAP.set(LEAVE_DATA_CREATION_PAGE_TITLE,ACCESS_LEVEL_3);
    PAGE_ACCESS_LEVEL_MAP.set(ALL_EMPLOYEE_TERMINATION_PAGE_TITLE,ACCESS_LEVEL_3);
    PAGE_ACCESS_LEVEL_MAP.set(EMPLOYEE_RATING_EDIT_DELETE_OPTION_PAGE_TITLE,ACCESS_LEVEL_3);
    PAGE_ACCESS_LEVEL_MAP.set(HOLIDAYLIST_FOR_ALLEMPLOYEES_WITH_EDIT_BUTTON,ACCESS_LEVEL_3);
    PAGE_ACCESS_LEVEL_MAP.set(EMPLOYEES_DATE_OF_BIRTH_UPLOAD,ACCESS_LEVEL_3);
    PAGE_ACCESS_LEVEL_MAP.set(APPLY_LEAVE_BY_HR,ACCESS_LEVEL_3);
    PAGE_ACCESS_LEVEL_MAP.set(HR_VIEW_EMPLOYEES_LEAVE_STATUS,ACCESS_LEVEL_3);
    PAGE_ACCESS_LEVEL_MAP.set(PENDING_LEAVES_UPDATE_FROM_BY_HR_LEVEL,ACCESS_LEVEL_3)
    PAGE_ACCESS_LEVEL_MAP.set(PENDING_LEAVES_DELETE_FROM_BY_HR_LEVEL,ACCESS_LEVEL_3)
    PAGE_ACCESS_LEVEL_MAP.set(HR_ACCESS_PENDING_LEAVES_STATUS,ACCESS_LEVEL_3)
    PAGE_ACCESS_LEVEL_MAP.set(LEAVES_BETA_ALL_EMPLOYEES_LEAVES_REPORT,ACCESS_LEVEL_3)
    PAGE_ACCESS_LEVEL_MAP.set(EMPLOYEES_WITHOUT_RM,ACCESS_LEVEL_3)
    

//warning mails
PAGE_ACCESS_LEVEL_MAP.set(WARNING_MAILS_CREATION_PAGE_TITLE,ACCESS_LEVEL_3);
PAGE_ACCESS_LEVEL_MAP.set(ALL_EMPLOYEE_WARNING_MAILS_PAGE_TITLE,ACCESS_LEVEL_3);



    //super admin
    PAGE_ACCESS_LEVEL_MAP.set(EMPLOYEE_DELETE_BUTTON,ACCESS_LEVEL_3);
